In [ ]:
#pip install torch

In [ ]:
import torch


x = torch.randn(2, 3, 4)
mul_ide = torch.eye(3)
a = torch.ones(3,3)
print(x)
print(torch.transpose(x, 1, 2))

tensor([[[-0.7016,  0.4943,  1.8187,  0.6331],
         [ 0.5315,  0.9525, -1.7193, -1.4939],
         [-1.6145, -1.0272,  0.4910,  0.5133]],

        [[ 0.0805, -0.1980,  0.8996,  3.1660],
         [ 0.1910, -0.4689,  1.7663,  1.6275],
         [ 1.0767,  0.4620, -1.3731, -1.4323]]])
tensor([[[-0.7016,  0.5315, -1.6145],
         [ 0.4943,  0.9525, -1.0272],
         [ 1.8187, -1.7193,  0.4910],
         [ 0.6331, -1.4939,  0.5133]],

        [[ 0.0805,  0.1910,  1.0767],
         [-0.1980, -0.4689,  0.4620],
         [ 0.8996,  1.7663, -1.3731],
         [ 3.1660,  1.6275, -1.4323]]])


In [ ]:
pi_matrix = torch.full((4,6), 3.1416)

print(torch.t(pi_matrix))

tensor([[3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416]])


In [ ]:
twototwelve = torch.linspace(2, 12, 10)
print(twototwelve)

tensor([ 2.0000,  3.1111,  4.2222,  5.3333,  6.4444,  7.5556,  8.6667,  9.7778,
        10.8889, 12.0000])
