## Experiment 1

#### - Installation

In [1]:
%pip install torch

import torch
import numpy as np

Note: you may need to restart the kernel to use updated packages.


#### - Tensor creation deletion

In [6]:
x = torch.randn(2, 3, 4)
mul_ide = torch.eye(3)
a = torch.ones(3,3)
print(x)
print(torch.transpose(x, 1, 2))

tensor([[[-0.0148,  0.5514, -0.8125, -1.7950],
         [-0.6829,  0.8346, -0.1333,  0.9661],
         [-0.3503,  1.4741, -0.6107, -0.2280]],

        [[-0.0708,  0.0817,  0.6399,  0.1640],
         [ 1.2369,  0.7681, -0.5579,  1.6404],
         [-0.7384,  0.5868, -1.5527, -0.6091]]])
tensor([[[-0.0148, -0.6829, -0.3503],
         [ 0.5514,  0.8346,  1.4741],
         [-0.8125, -0.1333, -0.6107],
         [-1.7950,  0.9661, -0.2280]],

        [[-0.0708,  1.2369, -0.7384],
         [ 0.0817,  0.7681,  0.5868],
         [ 0.6399, -0.5579, -1.5527],
         [ 0.1640,  1.6404, -0.6091]]])


In [7]:
del x
try:
    x
except NameError:
    print("Variable x is not defined")


Variable x is not defined


#### - Tensor manipulation 

In [20]:
x = torch.randn(3,3)
y = torch.randn(3,3)
print(x)
print(y)
x.mm(y)                                 #matrix multiplication


tensor([[ 0.0793,  0.9528,  1.8615],
        [-1.7882, -0.1156, -0.8044],
        [-0.0595,  0.7251, -0.5969]])
tensor([[-2.0373,  1.2502,  0.6588],
        [-0.0675,  0.8358,  0.4067],
        [-0.2500, -0.9502,  0.9762]])


tensor([[-0.6912, -0.8734,  2.2570],
        [ 3.8520, -1.5679, -2.0104],
        [ 0.2216,  1.0987, -0.3270]])

In [ ]:
twototwelve = torch.linspace(2, 12, 10)
print(twototwelve)

tensor([ 2.0000,  3.1111,  4.2222,  5.3333,  6.4444,  7.5556,  8.6667,  9.7778,
        10.8889, 12.0000])
